appName: "russian-cheatsheet-front"
listeningPort: 80

image:
  repository: "psegarra/russian-cheatsheet-front"

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

livenessProbe:
  path: /
readinessProbe:
  path: /

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "russiancheatsheet.com"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - russiancheatsheet.com
      secretName: russiancheatsheet-tls
